WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
        from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0
    
from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>

  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
    from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
    from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence    
from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
Traceback (most recent call last):
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluate.py", line 7, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from .training.deepspeed_training import training_main
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
from .training.deepspeed_training import training_main
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .training.deepspeed_training import training_main
    from .training.deepspeed_training import training_main  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
    from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0    
from .training.deepspeed_training import training_main  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from evaluation import BaseConfig, ModelForEvaluation, DEFAULT_CLASS, print_rank_0
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/__init__.py", line 2, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
        from .model import ModelForEvaluation
from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from .model import ModelForEvaluation
  File "/mnt/yrfs/xuyifan/GLM-130B/evaluation/model.py", line 5, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
    from SwissArmyTransformer.generation.autoregressive_sampling import filling_sequence
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/__init__.py", line 2, in <module>
from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .model_io import load_checkpoint, save_checkpoint    
from .model_io import load_checkpoint, save_checkpoint  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .training.deepspeed_training import training_main
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .training.deepspeed_training import training_main
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .training.deepspeed_training import training_main
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/__init__.py", line 1, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from .deepspeed_training import initialize_distributed, set_random_seed
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/deepspeed_training.py", line 30, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .model_io import load_checkpoint, save_checkpoint
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/model_io.py", line 20, in <module>
    from .torchvis import TorchVis
        from .torchvis import TorchVis  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
from .torchvis import TorchVis    

from .torchvis import TorchVis  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .torchvis import TorchVis
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
        from .utils import print_rank_0from .utils import print_rank_0

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .utils import print_rank_0
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/SwissArmyTransformer/training/utils.py", line 24, in <module>
    from .writer import SummaryWriter
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
from .writer import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .writer import SummaryWriter
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
from .writer import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .writer import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
        from tensorboardX import SummaryWriterfrom tensorboardX import SummaryWriter

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from tensorboardX import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .torchvis import TorchVis
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .torchvis import TorchVis
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .torchvis import TorchVis
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .summary import _clean_tag
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .writer import SummaryWriter
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
from .writer import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .writer import SummaryWriter
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/writer.py", line 16, in <module>
        from .proto.summary_pb2 import Summaryfrom .proto.summary_pb2 import Summary

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .comet_utils import CometLogger
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .summary import _clean_tag
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/summary.py", line 12, in <module>
        from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2    

from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    from .proto.summary_pb2 import Summary
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/summary_pb2.py", line 16, in <module>
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
        _descriptor.FieldDescriptor(_descriptor.FieldDescriptor(

  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
      File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import tensor_pb2 as tensorboardX_dot_proto_dot_tensor__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/tensor_pb2.py", line 16, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    from tensorboardX.proto import resource_handle_pb2 as tensorboardX_dot_proto_dot_resource__handle__pb2
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/tensorboardX/proto/resource_handle_pb2.py", line 36, in <module>
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates    
    _message.Message._CheckCalledFromGeneratedFile()_message.Message._CheckCalledFromGeneratedFile()

    TypeError_message.Message._CheckCalledFromGeneratedFile()TypeError
: : Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updatesDescriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updatesTypeError

: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _descriptor.FieldDescriptor(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError:     Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates_message.Message._CheckCalledFromGeneratedFile()

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 728409) of binary: /mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/python
Traceback (most recent call last):
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/yrfs/qinkai/miniconda3/envs/largescale/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/mnt/yrfs/xuyifan/GLM-130B/evaluate.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 728410)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 728411)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 728412)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 728413)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 728414)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 728415)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 728416)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-25_23:43:37
  host      : node14
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 728409)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
